import{automata,setAutomata}from"../automata.js";import{getConsoleText,reshape2DArray,setConsoleText}from"../utils.js";import{infoMap,nameMap,settingsMap}from"./config.js";
//! Respond to specific automata being selected
document.querySelectorAll(".select-btn").forEach((e=>{e.addEventListener("click",(function(){this.classList.contains("selected")||(document.querySelectorAll(".select-btn").forEach((e=>e.classList.remove("selected"))),this.classList.add("selected"),updateAutomataSelect(this.innerHTML),setAutomata(this.innerHTML))}))}));export function updateAutomataSelect(e){document.getElementById("automata-btn").innerHTML=nameMap[e]?nameMap[e]:e,document.querySelectorAll(".side-content").forEach((e=>e.style.display="none")),document.getElementById(infoMap[e]).style.display="block",document.querySelectorAll(".automata-settings").forEach((e=>e.style.display="none")),document.getElementById(settingsMap[e]).style.display="block"}
//! Neighborhood selectors
function createGrid(e){const t=document.getElementById(e),a=parseInt(t.querySelector(".row-select").value),n=parseInt(t.querySelector(".column-select").value),l=t.querySelector(".neighbor-grid"),o="block"==t.style.display;l.innerHTML="",t.style.display="block";let r=(l.closest(".automata-settings").clientWidth-2*(n-1))/n,s=r<=30?r:30;const i=s*n+2*(n-1);t.style.display=o?"block":"none",l.style.gridTemplateColumns=`repeat(${n}, ${s}px)`,l.style.gridTemplateRows=`repeat(${a}, ${s}px)`,l.style.width=i+"px";const u=Math.floor(a/2),d=Math.floor(n/2),c=automata.neighborhood;for(let e=0;e<a;e++)for(let t=0;t<n;t++){const a=document.createElement("input");a.type="checkbox",a.dataset.row=e-u,a.dataset.column=t-d,a.addEventListener("change",updateNeighborhood),-1!=JSON.stringify(c).indexOf(JSON.stringify([t-d,e-u]))&&(a.checked=!0),e===u&&t===d&&(a.checked=!1,a.disabled=!0),l.appendChild(a)}}function updateNeighborhood(e){let t=[];e.target.closest(".neighbor-grid").querySelectorAll("input").forEach((e=>{e.checked&&t.push([Number(e.dataset.column),Number(e.dataset.row)])})),automata.neighborhood=t}
//! Change in file load
document.getElementById("settings-btn").addEventListener("click",(()=>{if("object"==typeof settingsMap&&null!==settingsMap)for(let e of Object.values(settingsMap))try{createGrid(e,automata.neighborhood),window.addEventListener("resize",(()=>createGrid(e)))}catch(e){}})),document.querySelectorAll(".row-select").forEach((e=>e.addEventListener("input",(e=>{/^\d+$/.test(e.target.value)?createGrid(e.target.closest(".automata-settings").id):e.target.value=e.target.value.replace(/\D/g,"")})))),document.querySelectorAll(".column-select").forEach((e=>e.addEventListener("input",(e=>{/^\d+$/.test(e.target.value)?createGrid(e.target.closest(".automata-settings").id):e.target.value=e.target.value.replace(/\D/g,"")})))),document.getElementById("file-input").addEventListener("change",(e=>{const t=e.target.files[0];if(t){const e=new FileReader;e.onload=function(e){try{const t=JSON.parse(e.target.result);t.grid=reshape2DArray(t.grid,automata.grid.length,automata.grid[0].length),updateAutomataSelect(t.name),setAutomata(t.name,t.args,t.grid)}catch(e){console.log(e),document.getElementById("invalid-file-notice").style.display="block"}},e.readAsText(t)}else document.getElementById("invalid-file-notice").style.display="block"}),!1),
//! Life-like rules
document.getElementById("life-rule-input").addEventListener("input",(function(e){automata.setRules(e.target.value)})),
//! Elementary CA rules
document.getElementById("elementary-rule-input").addEventListener("input",(function(e){let t=Number(e.target.value.replace(/\D/g,""),10);t=t<0?0:t>255?255:t,e.target.value=t,automata.ruleNumber=t,automata.ruleMap=automata.parseEcaRule(automata.ruleNumber),automata.grid=automata.grid.map((e=>e.map((e=>1==e?e:2))))})),
//! Brian's Brain rules
document.getElementById("brain-rule-input").addEventListener("input",(function(e){automata.setRules(e.target.value)})),
//! Rock Paper Scissors Rule Input
document.getElementById("rps-rule-input").addEventListener("input",(function(e){let t=e.target.value;/^\d+$/.test(t)?(t=Number(t),0==t?setConsoleText("Invalid Rulestring!"):(automata.winCondition=e.target.value,"Invalid Rulestring!"==getConsoleText()&&setConsoleText("Valid Rulestring"))):(t=t.replace(/\D/g,""),t?e.target.value=t:setConsoleText("Invalid Rulestring!"))})),document.getElementById("rps-state-select").selectedIndex=0,document.getElementById("rps-state-select").onchange=e=>{automata.stateCount=Number(e.target.value)};