import{automata,ctx}from"../automata.js";import{midpointCircle,setConsoleText}from"../utils.js";import{cellSize,paused,changePaused,fillRadius,setFillRadius,setCellSize}from"./config.js";export let mouseX=0;export let mouseY=0;export var outlinePoints=[];
//! MOBILE COMPATIBILITY EVENTS
const moveEvents=["mousemove","touchmove"],downEvents=["mousedown","touchstart"],upEvents=["mouseup","touchend"],leaveEvents=["mouseleave","touchcancel"];function registerEvents(e,t,o){t.forEach((t=>e.addEventListener(t,o)))}
//! MOUSE FUNCTIONS
function updateMousePosition(e){const t=ctx.canvas.getBoundingClientRect();e.touches&&e.touches.length>0?(mouseX=e.touches[0].clientX-t.left,mouseY=e.touches[0].clientY-t.top):(mouseX=e.clientX-t.left,mouseY=e.clientY-t.top),automata.drawCursor()}let isDrawing=!1;function drawLoop(){isDrawing&&(automata.draw(),requestAnimationFrame(drawLoop))}export function registerCanvasCallbacks(e){registerEvents(e.canvas,moveEvents,updateMousePosition),registerEvents(e.canvas,downEvents,(()=>{isDrawing=!0,requestAnimationFrame(drawLoop)})),registerEvents(e.canvas,upEvents.concat(leaveEvents),(()=>{isDrawing=!1}))}
//! DRAGGEABLE WINDOWS
function triggerDragElement(e){let t=0,o=0,a=0,n=0;const s=window.innerWidth<420?120:.05*window.innerHeight;if(document.getElementById(e.id+"-header")){const t=document.getElementById(e.id+"-header");t.onmousedown=l,t.ontouchstart=l}else e.onmousedown=l,e.ontouchstart=l;function l(e){e.preventDefault(),e.stopPropagation(),t=e.clientX,o=e.clientY,document.onmouseup=c,document.onmousemove=i,document.ontouchend=c,document.ontouchmove=i}function i(l){l.preventDefault(),l.stopPropagation();const i=l.touches?l.touches[0].clientX:l.clientX,c=l.touches?l.touches[0].clientY:l.clientY;a=t-i,t=i,n=o>s?o-c:s,o=c;let r=e.offsetTop-n;e.style.top=(r<s?s:r)+"px",e.style.left=e.offsetLeft-a+"px"}function c(){document.onmouseup=null,document.onmousemove=null,document.ontouchend=null,document.ontouchmove=null}}
//! ACTIONS FOR KEY OR SETTING BUTTON INPUTS
function handleAction(e){switch(e){case".":case"Step":paused&&changePaused(),paused||changePaused(),setConsoleText("Stepped forward by 1 evolution");break;case"+":case"=":case"ArrowUp":case"Higher Fill Amt":setFillRadius(fillRadius+1);break;case"-":case"ArrowDown":case"Lower Fill Amt":setFillRadius(fillRadius-1<-1?-1:fillRadius-1);break;case"e":case"Higher Cell Size":setCellSize(cellSize+1);break;case"q":case"Lower Cell Size":setCellSize(cellSize-1<1?1:cellSize-1);break;case" ":case"p":case"Pause/Unpause":changePaused();break;case"Tab":case"r":case"Randomize Grid":automata.randomize(),automata.resetAnimationRequests(),setConsoleText("Randomized Grid");break;case"\\":case"Clear Grid":automata.grid=new Array(automata.rows).fill(null).map((e=>new Array(automata.cols).fill(automata.baseState?automata.baseState:0))),automata.ants&&(automata.ants=[]),automata.resetAnimationRequests(),setConsoleText("Cleared Grid");break;case"Shift":case"Change Pen Fill":automata.cycleDraw();break;case"Escape":case"Toggle Toolbar":const e=document.getElementById("toolbar");"block"!=e.style.display&&e.style.display?e.style.display="block":e.style.display="none";case"Save":automata.saveData(),setConsoleText("Saved automata data");break;case"Load":document.getElementById("load").style.display="block"}}
//! KEY INPUTS
document.querySelectorAll(".window").forEach((e=>{triggerDragElement(e);const t=window.innerWidth<420?120+Math.floor(Math.random()*window.innerHeight*.3):null,o=Math.floor(Math.random()*window.innerHeight*.5+.1*window.innerHeight),a=Math.floor(Math.random()*window.innerWidth*.6);e.style.top=(t||o)+"px",e.style.left=a+"px","startup"==e.id&&(e.style.display="block")})),document.querySelectorAll(".window-delete").forEach((e=>{registerEvents(e,["click","touchstart"],(()=>{e.closest(".window").style.display="none"}))})),document.querySelectorAll(".triggerbtn").forEach((e=>{registerEvents(e,["click","touchstart"],(()=>{document.getElementById(e.id.slice(0,-4)).style.display="block"}))})),document.querySelectorAll("button").forEach((function(e){e.addEventListener("focus",(function(){this.blur()}))})),window.addEventListener("keydown",(e=>{handleAction(e.key)})),
//! SETTINGS BUTTON PRESSED
document.querySelectorAll(".dropdown-option").forEach((e=>{e.addEventListener("click",(()=>{handleAction(e.querySelector(".option-name").innerHTML)}))}));