import{automata,ctx}from"../automata.js";import{midpointCircle,setConsoleText}from"../utils.js";import{cellSize,paused,changePaused,fillRadius,setFillRadius,setCellSize}from"./config.js";export let mouseX=0;export let mouseY=0;export var outlinePoints=[];
//! MOUSE FUNCTIONS
export function updateMousePosition(e){const t=ctx.canvas.getBoundingClientRect();mouseX=e.clientX-t.left,mouseY=e.clientY-t.top,outlinePoints=midpointCircle(Math.floor(mouseX/cellSize),Math.floor(mouseY/cellSize),fillRadius),automata.drawCursor()}let isDrawing=!1;function drawLoop(){isDrawing&&(automata.draw(),requestAnimationFrame(drawLoop))}export function registerCanvasCallbacks(e){e.canvas.addEventListener("mousemove",updateMousePosition),e.canvas.addEventListener("mousedown",(()=>{isDrawing=!0,requestAnimationFrame(drawLoop)})),e.canvas.addEventListener("mouseup",(()=>{isDrawing=!1})),e.canvas.addEventListener("mouseleave",(()=>{isDrawing=!1}))}
//! DRAGGEABLE WINDOWS
function triggerDragElement(e){let t=0,a=0,o=0,n=0;const l=.05*window.innerHeight;function i(e){e.preventDefault(),t=e.clientX,a=e.clientY,document.onmouseup=r,document.onmousemove=s}function s(i){i.preventDefault(),o=t-i.clientX,n=a-i.clientY,t=i.clientX,a=i.clientY<l?a:i.clientY;let s=e.offsetTop-n;e.style.top=(s<l?l:s)+"px",e.style.left=e.offsetLeft-o+"px"}function r(){document.onmouseup=null,document.onmousemove=null}document.getElementById(e.id+"-header")?document.getElementById(e.id+"-header").onmousedown=i:e.onmousedown=i}
//! ACTIONS FOR KEY OR SETTING BUTTON INPUTS
function handleAction(e){switch(e){case".":case"Step":paused&&changePaused(),paused||changePaused(),setConsoleText("Stepped forward by 1 evolution");break;case"+":case"=":case"ArrowUp":case"Higher Fill Amt":setFillRadius(fillRadius+1);break;case"-":case"ArrowDown":case"Lower Fill Amt":setFillRadius(fillRadius-1<-1?-1:fillRadius-1);break;case"e":case"Higher Cell Size":setCellSize(cellSize+1);break;case"q":case"Lower Cell Size":setCellSize(cellSize-1<1?1:cellSize-1);break;case" ":case"p":case"Pause/Unpause":changePaused();break;case"Tab":case"r":case"Randomize Grid":automata.randomize(),setConsoleText("Randomized Grid");break;case"Backspace":case"Clear Grid":automata.grid=new Array(automata.rows).fill(null).map((e=>new Array(automata.cols).fill(automata.baseState?automata.baseState:0))),automata.drawGrid(),setConsoleText("Cleared Grid");break;case"Shift":case"Change Pen Fill":automata.cycleDraw();break;case"Escape":case"Toggle Toolbar":const e=document.getElementById("toolbar");"block"!=e.style.display&&e.style.display?e.style.display="block":e.style.display="none";case"Save":automata.saveData(),setConsoleText("Saved automata data");break;case"Load":document.getElementById("load").style.display="block"}}
//! KEY INPUTS
document.querySelectorAll(".window").forEach((e=>{triggerDragElement(e),e.style.top=e.offsetTop+Math.floor(Math.random()*window.innerHeight*.5+.1*window.innerHeight)+"px",e.style.left=e.offsetLeft+Math.floor(Math.random()*window.innerWidth*.6)+"px"})),document.querySelectorAll(".window-delete").forEach((e=>{e.addEventListener("click",(()=>{e.closest(".window").style.display="none"}))})),document.querySelectorAll(".triggerbtn").forEach((e=>{e.addEventListener("click",(()=>{document.getElementById(e.id.slice(0,-4)).style.display="block"}))})),document.querySelectorAll("button").forEach((function(e){e.addEventListener("focus",(function(){this.blur()}))})),window.addEventListener("keydown",(e=>{handleAction(e.key)})),
//! SETTINGS BUTTON PRESSED
document.querySelectorAll(".dropdown-option").forEach((e=>{e.addEventListener("click",(()=>{handleAction(e.querySelector(".option-name").innerHTML)}))}));